ResturantDelivery/ResturantDelivery/Controllers/ordersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ValueGeneration.Internal;
using ResturantDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;


namespace ResturantDelivery.Controllers
{
    public class ordersController : Controller
    {

        private ResturentDeliveryContext context;
        public ordersController(ResturentDeliveryContext con)
        {
            context = con;

        }
        public IActionResult Index()
        {
            List<orders> orders= context.orderss.Include(m => m.Customer).Include(s=>s.Menu).ToList();
            return View(orders);
        }
        public IActionResult search(int searchkey)

        {

            var menu = context.orderss.Where(m =>m.customerid.Equals(searchkey)).Include(m => m.Customer).Include(b=>b.Menu).ToList();
            return View("Index",menu);
             
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.customers=context.customerss.OrderBy(c=>c.name).ToList();    
            return View();
        }
        [HttpPost]
        public IActionResult Add(orders mm)
        {
            context.orderss.Add(mm);
            context.SaveChanges();  
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int  id )
        {
orders mm= context.orderss.Where(m=>m.id==id).FirstOrDefault();
            context.Remove(mm);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
      
    } }
    

ResturantDelivery/ResturantDelivery/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ResturantDelivery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body{
            background-image:url(~/imgs/rahma.jfif);
        }
    </style>
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ResturantDelivery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetInt32("usid") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Add"> Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Login">Login</a>

                            </li>
                        }
                        @if (Context.Session.GetInt32("usid") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Menu"> Menu</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-action="Add" asp-controller="orders"> AddOrders </a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area=""  asp-action="ChangPassword" asp-controller="Customer">Chang Password</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Logout">Logout</a>


                            </li>
                        }
                        @if (Context.Session.GetString("cstatus") == "admin" && Context.Session.GetInt32("usid") != null)
                        {
                            <a class="nav-link text-dark" asp-area="" asp-action="Add" asp-controller="Menu"> Add </a>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ResturantDelivery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>